backend:
  name: github
  repo: tarpier/ovedoll.de-v2
  branch: master

publish_mode: editorial_workflow

media_folder: 'src/images' # Folder where user uploaded files should go
public_folder: 'static'
